added nav bar
ApprenticeGang/mars-mission-backend pull request #20
Opened 2020-09-17 14:59 UTC by nadiyaab

2020-09-17 15:12 UTC, MichaelWalker requested changes
Nice work!

Just a couple of really minor things! :)

2020-09-17 15:12 UTC, MichaelWalker commented on public/site.css
> +*{margin:0;padding:0;list-style:none;text-decoration:none}.header{width:100;height:80px;display:block;background-color:#101010}.inner_header{width:1000px;height:100%;display:block;margin:0 auto;backg
could we add CSS files to the `.gitignore`.
We don't really need them in source control because they can be generated on the fly! :)

2020-09-17 15:12 UTC, MichaelWalker commented on src/app.ts
> +const port = process.env['PORT'] || 3001;
I don't think we need this here - could you take it out again?

2020-09-17 15:12 UTC, MichaelWalker commented on src/app.ts
> +);
nice - looks good.

2020-09-17 15:12 UTC, MichaelWalker commented on templates/_base.html
> +    <!-- </header> -->
could we remove the commented out code?

2020-09-17 15:12 UTC, MichaelWalker commented on templates/_base.html
> +            </div>
At the moment every page will always have the title ADMIN PAGE - is that what you intended?

2020-09-17 15:12 UTC, MichaelWalker commented on templates/_base.html
> +            </ul>
close... but not quite the right syntax

a) could all of this be inside a `nav`?
b) the `li`s need to be the direct children of the `ul`.

so I think this should be 
```html
<nav>
    <ul>
        <li><a href="/home">Home</a></li>
        ....
    </ul>
</nav>
```

2020-09-17 15:23 UTC, nadiyaab commented on templates/_base.html
> +            </div>
For now, Louise and I will keep adding to the styles tomorrow

2020-09-18 00:02 UTC, MichaelWalker approved these changes

2020-09-18 09:07 UTC, merged