Adding in error handling - not finished
ApprenticeGang/mars-mission-backend pull request #22
Opened 2020-09-18 09:23 UTC by chillilauren

You can see in the code that I am asking for a specific error if getRoverImages doesn't work, and therefore the variable images shouldn't exist (I assume). But when I check this it comes back with a different error than the one I have specified, one that has been defined in nasaApiClient.ts

2020-09-18 13:43 UTC, MichaelWalker requested changes
This is looking pretty good to me!
Looks like it should pretty much work.

If you can tidy it up a little I'd be happy to merge! :)

2020-09-18 13:43 UTC, MichaelWalker commented on src/app.ts
> +require('express-async-errors');
we should probably `import` this instead

2020-09-18 13:43 UTC, MichaelWalker commented on src/app.ts
> +})
I don't think we need this if we've got the one above

2020-09-18 13:43 UTC, MichaelWalker commented on src/app.ts
> +})
this looks pretty good to me.
I guess this should catch basically anything.

If we want to be able to narrow it down any more then we can enhance it later.

2020-09-18 15:22 UTC, chillilauren commented on src/app.ts
> +require('express-async-errors');
I tried this before but wasn't sure what to write, tried this but it doesn't like it:
`import expressAsyncErrors from 'express-async-errors';`

2020-09-18 15:32 UTC, chillilauren commented on src/app.ts
> +})
I have ended up commenting out the bit 
`if (!images) {
     throw new Error('500: ApiError')
 }`

as this was doing nothing... in the network tab if the api doesn't work it sends a 404 code, but then that's not what it shows on the page for users to actually see

2020-09-21 12:08 UTC, MichaelWalker commented on src/app.ts
> +require('express-async-errors');
you should just be able to do `import 'express-async-errors';`

2020-09-21 12:09 UTC, MichaelWalker approved these changes

2020-09-21 12:09 UTC, MichaelWalker commented on src/app.ts
> +    // }
could you remove these commented lines?

2020-09-21 12:09 UTC, MichaelWalker commented on src/nasa/nasaApiClient.ts
> +
probably don't need this either.

2020-09-22 09:20 UTC, chillilauren commented
This says the checks are failing on ApiRoutes.ts which is not something I have added in here myself. I think this was a merge conflict.. I'm not sure how to fix this.

2020-09-22 09:38 UTC, MichaelWalker requested changes

2020-09-22 09:38 UTC, MichaelWalker commented on src/app.ts
> +
I don't think you meant to add this...
(its been moved to another file, so we don't want to add it back to here!)

2020-09-22 13:46 UTC, MichaelWalker approved these changes

2020-09-22 13:47 UTC, merged