Article API - Json printing articles from DB and test
ApprenticeGang/mars-mission-backend pull request #34
Opened 2020-09-22 12:54 UTC by Looease

2020-09-22 13:35 UTC, MichaelWalker requested changes
nice - a couple of small enhancements, but looking really good

2020-09-22 13:35 UTC, MichaelWalker commented on src/database/database.ts
> +};
You can make this a little nicer by adding types!

1) Create an interface for an article.
2) change getArticles to

```typescript
export const getArticles = (): Promise<Article[]> => {
    return db.select("*").from<Article>('news');
}
```

2020-09-22 13:35 UTC, MichaelWalker commented on src/apiRoutes.ts
> +    console.log(sqlResult);
could you remove the console log?

2020-09-22 13:35 UTC, MichaelWalker commented on src/app.test.ts
> +})
this is going to actually try to make a call to the database...
which will fail on CircleCI, because CircleCI doesn't have a database!

We'll need to mock out the `getArticles` function like we did in some of the other tests.

Could you also test the content of the response as well as just the status code?

(for examples of both of these check the tests for the status endpoint)

2020-09-23 11:35 UTC, Looease commented on src/app.test.ts
> +})
We've updated the response test - its quite basic but works

2020-09-23 11:58 UTC, MichaelWalker approved these changes

2020-09-23 11:58 UTC, MichaelWalker commented on src/app.test.ts
> +>>>>>>> 0cd64be08897ba530f1f9d6faaf05dee3a3ef9cc
Looks like we've got some merge conflict issues?

2020-09-23 12:41 UTC, merged